---
- hosts: all
  tasks:
    - name: reboot nodes
      become: yes
      shell: sleep 2 && shutdown -r now "Ansible reboot"
      async: 1
      poll: 0
      ignore_errors: true

    - debug:
        msg: 'ansible_ssh_host: {{ ansible_ssh_host }} ; inventory_hostname: {{ inventory_hostname }}'

    - name: wait for server to come back
      local_action: wait_for
      args:
        host: "{{ ansible_ssh_host | default(inventory_hostname) }}"
        port: 22
        state: started
        delay: 10
        connect_timeout: 5
        timeout: 300
