---
- hosts: all
  become: yes
  tasks:
    - name: Update servers (Red Hat)
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == 'RedHat'
    - name: Update servers (Debian)
      apt:
        name: '*'
        state: latest
        update_cache: yes
      when: ansible_os_family == 'Debian'
